FROM ubuntu:18.04

MAINTAINER hwon233@gmail.com

RUN apt update
RUN apt upgrade -y

ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y apache2
RUN apt install -y php php-mysql

RUN apt install -y openssl

COPY ssl_config.sh /ssl_config.sh
RUN chmod 777 /ssl_config.sh

EXPOSE 80 443

CMD ["apachectl", "-D", "FOREGROUND"]
