version: '3.3'

services:
  secured_web:
    build:
      context: .
      dockerfile: Dockerfile-https
    container_name: https
    depends_on:
      - db
    links:
      - "db:database"
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 8080:80
      - 443:443

  web:
    build:
      context: .
      dockerfile: Dockerfile-http
    container_name: http
    depends_on:
      - db
    links:
      - "db:database"
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 80:80

  db:
    container_name: mysql8
    image: mysql:8.0
    volumes:
      - ./sql/init.sql:/data/application/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
